import Tkinter
import random
import math

# Graphics commands.


def random_color():
    '''
    Generates random color values in hexadecimal format
    
    Arguments:    None
    
    Return value: String of color in hexadecimal format
    '''
    hexa = '0123456789abcdef'
    col_val = ['#']
    for i in range(6):
        col_val.append(random.choice(hexa))
    return ''.join(col_val)


#def draw_line(canvas, x1, y1, x2, y2, color):
    #line = canvas.create_line(x1, y1, x2, y2, fill = color)
    #return line


def draw_star(canvas, rad, num, color, c_x, c_y):
    '''
    Draws a star on the canvas
    
    Arguments:           canvas: canvas to drawn on
                         rad:    radius of the circle encompassing the star
                         num:    numper of points of the star
                         color:  color of the circle generated by random_color()
                         c_x, c_y: x and y coordinates of the center of star
    
    Return value:        list containing all the lines that make the star
    '''                     
    star = []
    xcord = []
    ycord = []
    ang = (2 * math.pi)/num
    for i in range(0, num):
        theta = math.pi/2 + (i * ang)
        dx = rad * math.cos(theta)
        dy = rad * math.sin(theta)
        xcord.append(c_x + dx)
        ycord.append(c_y - dy)
    dn = (num - 1)/2
    for i in range(0, num):
        if (i + dn) <= (num - 1):
            line = canvas.create_line(xcord[i], ycord[i], xcord[i + dn], \
                                      ycord[i + dn], fill = color)
        else:
            j = i + dn - num
            line = canvas.create_line(xcord[i], ycord[i], xcord[j], ycord[j], \
                                      fill = color)
        star.append(line)
    return star


# Event handlers.

def key_handler(event):
    '''Handle key presses.'''
    key = event.keysym
    global stars
    global col
    global N
    if key == 'q':
        quit()
    elif key == 'c':
        col = random_color()
    elif key == 'x':
        for star in stars:
            canvas.delete(star)
        stars = []
    elif key == 'plus':
        N += 2
    elif key == 'minus':
        if N != 5:
            N -= 2
            


def button_handler(event):
    '''Handle left mouse button click events.'''
    #global stars
    siz = random.randint(50, 100)
    sta = draw_star(canvas, siz, N, col, event.x, event.y)
    for i in sta:
        stars.append(i)
       


if __name__ == '__main__':
    root = Tkinter.Tk()
    root.geometry('800x800')
    canvas = Tkinter.Canvas(root, width = 800, height = 800)
    canvas.pack()
    stars = []
    col = random_color()
    N = 5
    # Bind events to handlers.
    root.bind('<Key>', key_handler)
    canvas.bind('<Button-1>', button_handler)
    # Start it up.
    root.mainloop()