import Tkinter
import random

# Graphics commands.


def random_color():
    '''
    Generates random color values in hexadecimal format
    
    Arguments:    None
    
    Return value: String of color in hexadecimal format
    '''
    hexa = '0123456789abcdef'
    col_val = ['#']
    for i in range(6):
        col_val.append(random.choice(hexa))
    return ''.join(col_val)


def draw_circle(canvas, color, dia, c_x, c_y):
    '''
    Draws a circle on the canvas
    
    Arguments:           canvas: canvas to drawn on
                         color:  color of the circle generated by random_color()
                         dia:    diameter of the circle
                         c_x, c_y: x and y coordinates of the center of circle
    
    Return value:        integer representing the circle object
    '''                     
    circle  = canvas.create_oval(c_x - (dia/2), c_y - (dia/2), \
                                 c_x + (dia/2), c_y + (dia/2), \
                                 outline = color, fill = color)
    return circle


# Event handlers.

def key_handler(event):
    '''Handle key presses.'''
    key = event.keysym
    global circles
    global col
    if key == 'q':
        quit()
    elif key == 'c':
        col = random_color()
    elif key == 'x':
        for circle in circles:
            canvas.delete(circle)
        circles = []
            


def button_handler(event):
    '''Handle left mouse button click events.'''
    #global circles
    siz = random.randint(10, 50)
    cir = draw_circle(canvas, col, siz, event.x, event.y)
    circles.append(cir)
        


if __name__ == '__main__':
    root = Tkinter.Tk()
    root.geometry('800x800')
    canvas = Tkinter.Canvas(root, width = 800, height = 800)
    canvas.pack()
    circles = []
    col = random_color()
    # Bind events to handlers.
    root.bind('<Key>', key_handler)
    canvas.bind('<Button-1>', button_handler)
    # Start it up.
    root.mainloop()
